# -*- coding: utf-8 -*-
"""API_test_connection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ol_o3l4Be9UClhg-lqejz59quR9qZ7ON
"""

import requests
import pandas as pd
import time
import logging


API_KEY = "de7303c846394ab1bb72f7465b697dd8"
BASE_URL = "https://api.rawg.io/api"

inp = "titels.csv"
df_scrap = pd.read_csv(inp)
games_names = df_scrap["Название"].tolist()

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

def get_json(url):
    response = requests.get(url)
    logging.info(f"Запрос: {url} | Статус-код: {response.status_code}")
    if response.status_code == 200:
        return response.json()
    else:
        logging.error(f"Ошибка при запросе {url}: статус {response.status_code}")
        return {}

# 1) /stores
stores_url = f"{BASE_URL}/stores?key={API_KEY}"
stores_data = get_json(stores_url)
stores_results = stores_data.get("results", [])
store_dict = {store["id"]: store["name"] for store in stores_results}

games_info = []

for name in games_names:
    logging.info(f"=== Обработка игры: {name} ===")

    #2) /games?search=...
    search_url = f"{BASE_URL}/games?key={API_KEY}&search={name}"
    search_data = get_json(search_url)
    results = search_data.get("results", [])
    if not results:
        logging.warning(f"Игра '{name}' не найдена!")
        continue

    game = results[0]
    game_id = game["id"]
    logging.info(f"Выбрана игра: {game.get('name')} (ID: {game_id})")

    #3) /games/{id}
    detail_url = f"{BASE_URL}/games/{game_id}?key={API_KEY}"
    detail_data = get_json(detail_url)

    game_title    = detail_data.get("name", name)
    released      = detail_data.get("released")
    rating        = detail_data.get("rating")
    playtime      = detail_data.get("playtime")
    metacritic    = detail_data.get("metacritic")
    ratings_count = detail_data.get("ratings_count")
    description   = detail_data.get("description_raw", "")[:150]
    publishers    = ", ".join(pub["name"] for pub in detail_data.get("publishers", []))
    developers    = ", ".join(dev["name"] for dev in detail_data.get("developers", []))
    esrb_rating   = detail_data.get("esrb_rating", {}).get("name") if detail_data.get("esrb_rating") else None
    tags          = ", ".join(tag["name"] for tag in detail_data.get("tags", []))
    added         = detail_data.get("added")
    platforms_list = detail_data.get("platforms", [])
    platform_names = [p.get("platform", {}).get("name") for p in platforms_list if p.get("platform", {}).get("name")]

    #4) /games/{id}/achievements
    achievements_url = f"{BASE_URL}/games/{game_id}/achievements?key={API_KEY}"
    achievements_data = get_json(achievements_url)
    achievements_count = achievements_data.get("count", 0)

    #5) /games/{id}/stores
    stores_url = f"{BASE_URL}/games/{game_id}/stores?key={API_KEY}"
    stores_data = get_json(stores_url)
    stores_results = stores_data.get("results", [])
    store_names = [store_dict.get(s.get("store_id"), f"Unknown ({s.get('store_id')})") for s in stores_results]

    #6) /games/{id}/development-team
    dev_team_url = f"{BASE_URL}/games/{game_id}/development-team?key={API_KEY}"
    dev_team_data = get_json(dev_team_url)
    dev_team_results = dev_team_data.get("results", [])
    dev_team_count = len(dev_team_results)

    game_info = {
        "ID": game_id,
        "Название": game_title,
        "Дата выхода": released,
        "Рейтинг": rating,
        "Playtime": playtime,
        "Metacritic": metacritic,
        "Оценок": ratings_count,
        "Описание": description,
        "Издатели": publishers,
        "Возрастной рейтинг (ESRB)": esrb_rating,
        "Разработчики": developers,
        "Теги": tags,
        "Популярность (added)": added,
        "Достижения (кол-во)": achievements_count,
        "Платформы": ", ".join(platform_names),
        "Магазины": ", ".join(store_names),
        "Команда разработчиков (кол-во)": dev_team_count
    }

    games_info.append(game_info)

    time.sleep(0.2)


df = pd.DataFrame(games_info)
output_filename = "games_data.csv"
df.to_csv(output_filename, index=False, encoding="utf-8-sig")

print(f"Данные успешно сохранены в {output_filename}")