# -*- coding: utf-8 -*-
"""parser merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDmNjVYnqQ2-ALsTlqti5JxD7RgPmUr3
"""

import pandas as pd

df = pd.read_csv('vgchartz_games .csv')
df

df1 = pd.read_csv('gg_deals_games .csv')
df1

merged_df = pd.merge(df, df1, left_on = 'Название', right_on = 'Название', how = 'inner')
merged_df

merged_df = merged_df.drop(columns = ['Unnamed: 0_x', 'Unnamed: 0_y'])

merged_df = merged_df.drop_duplicates(subset = 'Название', keep = 'first')

merged_df = merged_df.dropna()
merged_df