# -*- coding: utf-8 -*-
"""Копия блокнота "Untitled7.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13a9zvcTGw1yoReqpB5HLb9GUd6CtJZ9A
"""

import pandas as pd

df_original = pd.read_csv("pars_games_unique.csv")
df_api = pd.read_csv("games_api_data.csv")

df_merged = pd.merge(df_original, df_api, on="Название", how="left")
df_merged.replace(0, pd.NA, inplace=True)

df_merged.to_csv("df_itog.csv", index=False, encoding="utf-8-sig")
print("Файл 'df_itog.csv' успешно сохранен!")